### ISSUE TITLE
mismatched indentation

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei-burp-plugin#18]
current indentation:

```yaml
id: template-id

info:
  name: Template Name
  author: geekboy
  severity: info
  description: description
  reference: https://
  tags: tags

requests:
- raw:
  - |+
    GET /test HTTP/1.1
    Host: {{Hostname}}

  matchers-condition: and
  matchers:
  - type: word
    part: header
    words:
    - server

  - type: status
    status:
    - 200
```

expected indentation:

```yaml
id: template-id

info:
  name: Template Name
  author: geekboy
  severity: info
  description: description
  reference: https://
  tags: tags

requests:
  - raw:
      - |+
        GET /test HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: word
        words:
          - server

      - type: status
        status:
          - 200
```
</details>

```console
yamllint test.yaml

  12:1      error    wrong indentation: expected 2 but found 0  (indentation)
  13:3      error    wrong indentation: expected 4 but found 2  (indentation)
  36:3      error    wrong indentation: expected 4 but found 2  (indentation)
  39:5      error    wrong indentation: expected 6 but found 4  (indentation)
  42:5      error    wrong indentation: expected 6 but found 4  (indentation)
```
